resources:
- ../../base

namespace: dev

patches:
- path: replicas.yaml

configMapGenerator:
- name: backend-config-map
  behavior: merge #or: replace
  env: config.properties

images:
  - name: docker-repo/webapp
    newTag: latest