resources:
- deployment.yaml
- service.yaml

commonLabels:
  app: webapp

commonAnnotations:
  key1: value1

namePrefix: epc-

nameSuffix: -v1

configMapGenerator:
- name: backend-config-map
  env: config.properties

secretGenerator:
- name: db-password
  literals:
  - username=user123
  - password=password123
  # files:
# - secretfile.txt
#keep your kustomization.yaml or secret files safe: SealedSecrets, Vault etc

# generatorOptions:
#   disableNameSuffixHash: true
