apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment-v1
  namespace: default
  labels:
    app: webapp
  annotations:
    key1: value1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: mycontainer
        image: "docker-repo/webapp:stable"
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: webapp-configmapv1.0
        resources:
          requests:
            memory: "16Mi" 
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"