apiVersion: v1
kind: Secret
type: Opaque
metadata:
  annotations:
    key1: value1
  labels:
    app: webapp
  name: epc-db-password-v1
data: # probably not a good idea to keep in the repo, what are best practices here?
  password: cGFzc3dvcmQxMjM=
  username: dXNlcjEyMw==