apiVersion: v1
kind: Service
metadata:
  name: epc-backend-service-v1
  namespace: default
  labels:
    app: webapp
  annotations:
    key1: value1
spec:
  selector:
    app: webapp
  ports:
  - name: http
    port: 8080